### ISSUE TITLE
ssh connect error

### ISSUE THREAD

**Issue by zihaozhu93** [airbnb/omniduct#113]
>>> from omniduct import Duct
>>> DB_HOST = "data03"
>>> remote = Duct.for_protocol('ssh')(host=DB_HOST, port=22)
>>> remote.connect()

SSHClient: Connecting: Connecting to data03:22.Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/venv/lib/python3.6/site-packages/omniduct/remotes/base.py", line 159, in connect
    Duct.connect(self)
  File "/data/venv/lib/python3.6/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/venv/lib/python3.6/site-packages/omniduct/utils/debug.py", line 275, in logging_scope
    raise_with_traceback(e)
  File "/data/venv/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/data/venv/lib/python3.6/site-packages/omniduct/utils/debug.py", line 271, in logging_scope
    f = func(*args, **kwargs)
  File "/data/venv/lib/python3.6/site-packages/omniduct/duct.py", line 469, in connect
    raise_with_traceback(e)
  File "/data/venv/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "/data/venv/lib/python3.6/site-packages/omniduct/duct.py", line 466, in connect
    self._connect()
  File "/data/venv/lib/python3.6/site-packages/omniduct/remotes/ssh.py", line 162, in _connect
    '{}\n\n Please report this!'.format(cmd)
AssertionError: Unexpected failure to establish a connection with the remote host with command:
 ssh work@data03 -MT -S /home/work/.ssh/omniduct/work@data03 -o ControlPersist=yes -o StrictHostKeyChecking=no -o NoHostAuthenticationForLocalhost=yes -o ServerAliveInterval=60 -o ServerAliveCountMax=2 'exit'

 Please report this!

but,ssh connection use cli works,

**Comment by zihaozhu93** [comment]
.
